# Generated by Django 3.2.3 on 2022-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowersection',
            name='member_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uppersection',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
