# Generated by Django 4.0.1 on 2022-02-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_auto_20220206_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowersection',
            name='member_desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
