# Generated by Django 4.0.2 on 2022-03-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_midsection_meet_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.RemoveField(
            model_name='midsection',
            name='meet_team',
        ),
    ]
