# Generated by Django 4.0.2 on 2022-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_delete_navbar_remove_midsection_meet_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowersection',
            name='member_contact',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='lowersection',
            name='member_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
