# Generated by Django 4.0.2 on 2022-03-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_lowersection_member_contact_lowersection_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowersection',
            name='member_major',
            field=models.CharField(default='', max_length=250),
        ),
    ]
