# Generated by Django 3.2.3 on 2022-03-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_lowersection_member_major'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midsection',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='midsection',
            name='game_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='midsection',
            name='movie_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='midsection',
            name='about_us',
            field=models.TextField(blank=True, default='Enter text about us.'),
        ),
    ]
