# Generated by Django 3.2.3 on 2022-03-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0008_auto_20220314_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowersection',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='midsection',
            options={},
        ),
    ]
