# Generated by Django 3.2.3 on 2022-03-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_alter_lowersection_member_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midsection',
            options={'verbose_name': 'Middle Section', 'verbose_name_plural': 'Middle Sections'},
        ),
        migrations.AlterModelOptions(
            name='pagefooter',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footers'},
        ),
        migrations.AlterModelOptions(
            name='uppersection',
            options={'verbose_name': 'Upper Section', 'verbose_name_plural': 'Upper Sections'},
        ),
    ]
