# Generated by Django 4.0.2 on 2022-04-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0012_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
