# Generated by Django 4.0.2 on 2022-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowersection',
            name='member_major',
            field=models.IntegerField(choices=[(0, 'Web Development'), (1, 'Software Development'), (3, 'Digital Media')], default=0),
        ),
    ]
