# Generated by Django 4.0.2 on 2022-04-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_section_description', models.TextField(default='', max_length=750)),
            ],
        ),
    ]
