# Generated by Django 4.0.2 on 2022-04-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0014_alter_lowersection_member_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowersection',
            name='member_major',
            field=models.IntegerField(choices=[(0, 'Web Development'), (1, 'Software Development'), (2, 'Digital Media')], default=0),
        ),
    ]
