# Generated by Django 4.0.2 on 2022-04-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0014_studentsection'),
        ('LandingPage', '0015_alter_lowersection_member_major'),
    ]

    operations = [
    ]
