# Generated by Django 4.0.2 on 2022-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0016_merge_20220419_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagefooter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uppersection',
            options={},
        ),
    ]
