# Generated by Django 4.0.2 on 2022-04-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0017_alter_midsection_options_alter_pagefooter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midsection',
            name='game_photo',
        ),
        migrations.RemoveField(
            model_name='midsection',
            name='movie_photo',
        ),
    ]
