# Generated by Django 4.0.2 on 2022-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0018_remove_midsection_game_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowersection',
            name='member_desc',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='lowersection',
            name='member_major',
            field=models.IntegerField(choices=[(0, 'Web Development'), (1, 'Software Development'), (2, 'Digital Media'), (3, 'Interactive, Digital, & 3D Technology')], default=0),
        ),
    ]
