# Generated by Django 4.0.2 on 2022-04-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0019_alter_lowersection_member_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowersection',
            name='member_portfolio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='lowersection',
            name='member_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
